data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3

  group_names:
    group_1: benchmark_separableConvolve2D_inputSize
    group_2: benchmark_separableConvolve_2D_inputSize
    group_3: benchmark_convolve2D_inputSize


  variants: ['channelFirst', 'channelLast']
  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 50
      stop: 2050
      step: 50
    values: []

graph:
  title: SeparableConvolve Implementations vs Explicit Implementation

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ms)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelFirst: separableConvolve2D (Channel First)
      group_1_channelLast: separableConvolve2D (Channel Last)
      group_2_channelFirst: separableConvolve [N=2] (Channel First)
      group_2_channelLast: separableConvolve [N=2] (Channel Last)
      group_3_channelFirst: convolve2D (Channel First)
      group_3_channelLast: convolve2D (Channel Last)

  line_style:
    key: '{variant}'
    entries:
      channelFirst: "-"
      channelLast: ":"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#55868C"
      group_2: "#EEC584"
      group_3: "#CE4257"

