data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3
    - group_4
    - group_5

  group_names:
    group_1: benchmark_convolve1D_v1_inputSize
    group_2: benchmark_convolve1D_v2_inputSize
    group_3: benchmark_convolve1D_v3_inputSize
    group_4: benchmark_convolve1D_v4_inputSize
    group_5: benchmark_convolve1D_v5_inputSize

  variants:
    - channelFirst
  #  - channelLast

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 50
      stop: 2050
      step: 150
    values: []

graph:
  title: Different Implementations of convolve1D

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ns)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelFirst: convolve1D V.1 (Channel First)
      group_1_channelLast: convolve1D V.1 (Channel Last)
      group_2_channelFirst: convolve1D V.2 (Channel First)
      group_2_channelLast: convolve1D V.2 (Channel Last)
      group_3_channelFirst: convolve1D V.3 (Channel First)
      group_3_channelLast: convolve1D V.3 (Channel Last)
      group_4_channelFirst: convolve1D V.4 (Channel First)
      group_4_channelLast: convolve1D V.4 (Channel Last)
      group_5_channelFirst: convolve1D V.5 (Channel First)
      group_5_channelLast: convolve1D V.5 (Channel Last)

  line_style:
    key: '{variant}'
    entries:
      channelFirst: "-"
      channelLast: ":"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#55868C"
      group_2: "#EEC584"
      group_3: "#CE4257"
      group_4: "#FF0000"
      group_5: "#9900FF"

