data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1

  group_names:
    group_1: benchmark_convolve1D_inputSize

  variants:
    - channelFirst
    - channelLast
    - channelFirst_v2
    - channelLast_v2
    - channelFirst_v3
    - channelLast_v3
    - channelFirst_v4
    - channelLast_v4
    - channelFirst_v5
    - channelLast_v5

  aggregates: ['min']
  specializations: ['INPUT_TYPE']
  x:
    type: np.arange
    attrs:
      start: 50
      stop: 2050
      step: 150
    values: []

graph:
  title: Different Implementations of convolve1D

  x_axis:
    label: Size S
    mode: log

  y_axis:
    label: Minimum Time (ns)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelFirst: convolve1D V.1 (Channel First)
      group_1_channelLast: convolve1D V.1 (Channel Last)
      group_1_channelFirst_v2: convolve1D V.2 (Channel First)
      group_1_channelLast_v2: convolve1D V.2 (Channel Last)
      group_1_channelFirst_v3: convolve1D V.3 (Channel First)
      group_1_channelLast_v3: convolve1D V.3 (Channel Last)
      group_1_channelFirst_v4: convolve1D V.4 (Channel First)
      group_1_channelLast_v4: convolve1D V.4 (Channel Last)
      group_1_channelFirst_v5: convolve1D V.5 (Channel First)
      group_1_channelLast_v5: convolve1D V.5 (Channel Last)

  line_style:
    key: '{variant}'
    entries:
      channelFirst: "-"
      channelLast: ":"
      channelFirst_v2: "-"
      channelLast_v2: ":"
      channelFirst_v3: "-"
      channelLast_v3: ":"
      channelFirst_v4: "-"
      channelLast_v4: ":"
      channelFirst_v5: "-"
      channelLast_v5: ":"

  line_color:
    key: '{variant}'
    entries:
      channelFirst: "#55868C"
      channelLast: "#55868C"
      channelFirst_v2: "#EEC584"
      channelLast_v2: "#EEC584"
      channelFirst_v3: "#CE4257"
      channelLast_v3: "#CE4257"
      channelFirst_v4: "#FF0000"
      channelLast_v4: "#FF0000"
      channelFirst_v5: "#9900FF"
      channelLast_v5: "#9900FF"

