data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3
    - group_4

  group_names:
    group_1: benchmark_separableConvolve1D_kernelSize
    group_2: benchmark_separableConvolveND_1D_kernelSize
    group_3: benchmark_separableConvolve_1D_kernelSize
    group_4: benchmark_convolve1D_kernelSize


  variants: ['channelFirst', 'channelLast']
  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 1
      stop: 21
      step: 1
    values: []

graph:
  title: SeparableConvolve Implementations vs Explicit Implementation

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (µs)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelFirst: 'separableConvolve1D (Channel First)'
      group_1_channelLast:  'separableConvolve1D (Channel Last)'
      group_2_channelFirst: 'separableConvolveND [N=1] (Channel First)'
      group_2_channelLast:  'separableConvolveND [N=1] (Channel Last)'
      group_3_channelFirst: 'separableConvolve [N=1] (Channel First)'
      group_3_channelLast:  'separableConvolve [N=1] (Channel Last)'
      group_4_channelFirst: 'convolve1D (Channel First)'
      group_4_channelLast:  'convolve1D (Channel Last)'

  line_style:
    key: '{variant}'
    entries:
      channelFirst: "-"
      channelLast: ":"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#55868C"
      group_2: "#EEC584"
      group_3: "#9900FF"
      group_4: "#CE4257"

