data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3
    - group_4
    - group_5

  group_names:
    group_1: benchmark_convolve2D_v1_inputSize
    group_2: benchmark_convolve2D_v2_inputSize
    group_3: benchmark_convolve2D_v3_inputSize
    group_4: benchmark_convolve2D_v4_inputSize
    group_5: benchmark_convolve2D_v5_inputSize

  variants:
    - channelFirst

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 1500
      stop: 2050
      step: 50
    values: []

graph:
  figsize: [6, 10]
  font_legend_size: 12
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ms)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelFirst: c2D-v1-cF
      group_2_channelFirst: c2D-v2-cF
      group_3_channelFirst: c2D-v3-cF
      group_4_channelFirst: c2D-v4-cF
      group_5_channelFirst: c2D-v5-cF

  line_style:
    key: '{variant}'
    entries:
      channelFirst: "-"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#ff0000"
      group_2: "#ffa500"
      group_3: "#cccc00"
      group_4: "#008000"
      group_5: "#0000ff"

