data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3
    - group_4

  group_names:
    group_1: benchmark_separableConvolve1D_kernelSize
    group_2: benchmark_separableConvolveND_1D_kernelSize
    group_3: benchmark_separableConvolve_1D_kernelSize
    group_4: benchmark_convolve1D_kernelSize


  variants: ['channelFirst', 'channelLast']
  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 1
      stop: 21
      step: 1
    values: []

graph:
  figsize: [6, 10]
  font_legend_size: 12
  title: ""

  x_axis:
    label: Kernelsize K
    mode: normal

  x:
    type: list
    attrs:
      start: 1500
      stop: 2050
      step: 50
    values: [1, 5, 10, 15, 20]

  y_axis:
    label: Minimum Time (µs)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelFirst: sC1D-kS-cF
      group_1_channelLast:  sC1D-kS-cL
      group_2_channelFirst: sCN1D-kS-cF
      group_2_channelLast:  sCN1D-kS-cL
      group_3_channelFirst: sC1-kS-cF
      group_3_channelLast:  sC1-kS-cL
      group_4_channelFirst: c1D-kS-cF
      group_4_channelLast:  c1D-kS-cL

  line_style:
    key: '{variant}'
    entries:
      channelFirst: "-"
      channelLast: ":"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#ff0000"
      group_2: "#ffa500"
      group_3: "#cccc00"
      group_4: "#4b0082"

