data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3
    - group_4
    - group_5
    - group_6

  group_names:
    group_1: benchmark_convolve1D_v1_inputSize
    group_2: benchmark_convolve1D_v2_inputSize
    group_3: benchmark_convolve1D_v3_inputSize
    group_4: benchmark_convolve1D_v4_inputSize
    group_5: benchmark_convolve1D_v5_inputSize
    group_6: benchmark_convolve1D_v6_inputSize

  variants:
    - channelLast

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 1500
      stop: 2050
      step: 50
    values: []

graph:
  figsize: [6, 10]
  font_legend_size: 12
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (µs)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelLast: c1D-v1-cL
      group_2_channelLast: c1D-v2-cL
      group_3_channelLast: c1D-v3-cL
      group_4_channelLast: c1D-v4-cL
      group_5_channelLast: c1D-v5-cL
      group_6_channelLast: c1D-v6-cL

  line_style:
    key: '{variant}'
    entries:
      channelLast: "-"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#55868C"
      group_2: "#EEC584"
      group_3: "#CE4257"
      group_4: "#FF0000"
      group_5: "#9900FF"
      group_6: "#000000"

