data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3
    - group_4

  group_names:
    group_1: benchmark_separableConvolve1D_inputSize
    group_2: benchmark_separableConvolveND_1D_inputSize
    group_3: benchmark_separableConvolve_1D_inputSize
    group_4: benchmark_convolve1D_inputSize


  variants: ['channelFirst', 'channelLast']
  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 1000
      stop: 1550
      step: 50
    values: []

graph:
  figsize: [6, 10]
  font_legend_size: 12
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (µs)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelFirst: sC1D-iS-cF
      group_1_channelLast:  sC1D-iS-cL
      group_2_channelFirst: sCN1D-iS-cF
      group_2_channelLast:  sCN1D-iS-cL
      group_3_channelFirst: sC1-iS-cF
      group_3_channelLast:  sC1-iS-cL
      group_4_channelFirst: c1D-iS-cF
      group_4_channelLast:  c1D-iS-cL

  line_style:
    key: '{variant}'
    entries:
      channelFirst: "-"
      channelLast: ":"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#55868C"
      group_2: "#EEC584"
      group_3: "#9900FF"
      group_4: "#CE4257"

