data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3
    - group_4
    - group_5

  group_names:
    group_1: benchmark_convolve2D_v1_inputSize
    group_2: benchmark_convolve2D_v2_inputSize
    group_3: benchmark_convolve2D_v3_inputSize
    group_4: benchmark_convolve2D_v4_inputSize
    group_5: benchmark_convolve2D_v5_inputSize

  variants:
    - channelFirst

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 1500
      stop: 2050
      step: 50
    values: []

graph:
  figsize: [6, 10]
  font_legend_size: 12
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ms)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelFirst: convolve2D V.1
      group_2_channelFirst: convolve2D V.2
      group_3_channelFirst: convolve2D V.3
      group_4_channelFirst: convolve2D V.4
      group_5_channelFirst: convolve2D V.5

  line_style:
    key: '{variant}'
    entries:
      channelFirst: "-"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#55868C"
      group_2: "#EEC584"
      group_3: "#CE4257"
      group_4: "#FF0000"
      group_5: "#9900FF"

