data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1
    - group_2
    - group_3
    - group_4
    - group_5
    - group_6

  group_names:
    group_1: benchmark_convolve1D_v1_inputSize
    group_2: benchmark_convolve1D_v2_inputSize
    group_3: benchmark_convolve1D_v3_inputSize
    group_4: benchmark_convolve1D_v4_inputSize
    group_5: benchmark_convolve1D_v5_inputSize
    group_6: benchmark_convolve1D_v6_inputSize

  variants:
    - channelLast

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 50
      stop: 2050
      step: 150
    values: []

graph:
  title: Different Implementations of convolve1D (channelLast)

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (µs)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_channelLast: convolve1D V.1
      group_2_channelLast: convolve1D V.2
      group_3_channelLast: convolve1D V.3
      group_4_channelLast: convolve1D V.4
      group_5_channelLast: convolve1D V.5
      group_6_channelLast: convolve1D V.6

  line_style:
    key: '{variant}'
    entries:
      channelLast: "-"

  line_color:
    key: '{group_id}'
    entries:
      group_1: "#55868C"
      group_2: "#EEC584"
      group_3: "#CE4257"
      group_4: "#FF0000"
      group_5: "#9900FF"
      group_6: "#000000"

