data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1

  group_names:
    group_1: benchmark_xstrided_view_copy_paddingStride_Z

  variants:
    - assign
    - iterator
    - operatorCallAgainstCache
    - operatorCallCacheAligned
    - rawAgainstCache
    - rawCacheAligned

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 50
      stop: 1100
      step: 100
    values: []

graph:
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ms)
    mode: normal

  legend:
    key: '{variant}'
    entries:
      assign: sv-c-pSZ-a
      iterator: sv-c-pSZ-i
      operatorCallAgainstCache: sv-c-pSZ-cAC
      operatorCallCacheAligned: sv-c-pSZ-cCA
      rawAgainstCache: sv-c-pSZ-rAC
      rawCacheAligned: sv-c-pSZ-rCA

  line_style:
    key: '{group_id}'
    entries:
      group_1: "-"

  line_color:
    key: '{variant}'
    entries:
      assign: "#ff0000"
      iterator: "#ffa500"
      operatorCallAgainstCache: "#cccc00"
      operatorCallCacheAligned: "#008000"
      rawAgainstCache: "#0000ff"
      rawCacheAligned: "#4b0082"

