data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1

  group_names:
    group_1: benchmark_normalizing

  variants:
    - amax
    - amax_unpacked

  aggregates: ['min']
  specializations: ['xt::xarray<float>', 'xt::xtensor<float, 3>']
  x:
    type: np.arange
    attrs:
      start: 1
      stop: 50
      step: 3
    values: []

graph:
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ns)
    mode: log

  legend:
    key: '{specialization}_{variant}'
    entries:
      xt::xarray<float>_amax: xarray, input / amax(input)
      xt::xarray<float>_amax_unpacked: xarray, input / amax(input)[0]
      xt::xtensor<float, 3>_amax: xtensor, input / amax(input)
      xt::xtensor<float, 3>_amax_unpacked: xtensor, input / amax(input)[0]

  line_style:
    key: '{variant}'
    entries:
      amax: "-"
      amax_unpacked: "-"

  line_color:
    key: '{specialization}_{variant}'
    entries:
      xt::xarray<float>_amax: "#ea0909"
      xt::xarray<float>_amax_unpacked: "#9a0707"
      xt::xtensor<float, 3>_amax: "#8fa4c3"
      xt::xtensor<float, 3>_amax_unpacked: "#283347"

