data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1

  group_names:
    group_1: benchmark_xstrided_view_copy_complete_Y

  variants:
    - assign
    - iterator
    - operatorCallAgainstCache
    - operatorCallCacheAligned
    - rawAgainstCache
    - rawCacheAligned

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 50
      stop: 1100
      step: 100
    values: []

graph:
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ms)
    mode: normal

  legend:
    key: '{variant}'
    entries:
      assign: assign operator
      iterator: std::copy with iterators
      operatorCallAgainstCache: copy via operator() against cache
      operatorCallCacheAligned: copy via operator() cache aligned
      rawAgainstCache: raw data copy against cache
      rawCacheAligned: raw data copy cache aligned

  line_style:
    key: '{group_id}'
    entries:
      group_1: "-"

  line_color:
    key: '{variant}'
    entries:
      assign: "#ff0000"
      iterator: "#ffa500"
      operatorCallAgainstCache: "#cccc00"
      operatorCallCacheAligned: "#008000"
      rawAgainstCache: "#0000ff"
      rawCacheAligned: "#4b0082"

