data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1

  group_names:
    group_1: benchmark_view_copy_paddingStride_Y

  variants:
    - assign
    - iterator
    - operatorCallAgainstCache
    - operatorCallCacheAligned
    - rawAgainstCache
    - rawCacheAligned

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 50
      stop: 1100
      step: 100
    values: []

graph:
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ms)
    mode: normal

  legend:
    key: '{variant}'
    entries:
      assign: v-c-pSY-a
      iterator: v-c-pSY-i
      operatorCallAgainstCache: v-c-pSY-cAC
      operatorCallCacheAligned: v-c-pSY-cCA
      rawAgainstCache: v-c-pSY-rAC
      rawCacheAligned: v-c-pSY-rCA

  line_style:
    key: '{group_id}'
    entries:
      group_1: "-"

  line_color:
    key: '{variant}'
    entries:
      assign: "#ff0000"
      iterator: "#ffa500"
      operatorCallAgainstCache: "#cccc00"
      operatorCallCacheAligned: "#008000"
      rawAgainstCache: "#0000ff"
      rawCacheAligned: "#4b0082"

