data:
  key: '{group_name}_{variant}<{specialization}>/{x}_{aggregate}'
  group_ids:
    - group_1

  group_names:
    group_1: benchmark_xstrided_view_copy_complete_X

  variants:
    - assign
    - iterator
    - operatorCallAgainstCache
    - operatorCallCacheAligned
    - rawAgainstCache
    - rawCacheAligned

  aggregates: ['min']
  specializations: ['float']
  x:
    type: np.arange
    attrs:
      start: 50
      stop: 1100
      step: 100
    values: []

graph:
  title: ""

  x_axis:
    label: Size S
    mode: normal

  y_axis:
    label: Minimum Time (ms)
    mode: normal

  legend:
    key: '{group_id}_{variant}'
    entries:
      group_1_assign: assign operator
      group_1_iterator: std::copy with iterators
      group_1_operatorCallAgainstCache: copy to xstrided_view via operator() against cache
      group_1_operatorCallCacheAligned: copy to xstrided_view via operator() cache aligned
      group_1_rawAgainstCache: raw data copy against cache
      group_1_rawCacheAligned: raw data copy cache aligned

  line_style:
    key: '{variant}'
    entries:
      assign: "-"
      iterator: "-"
      operatorCallAgainstCache: "-"
      operatorCallCacheAligned: "-"
      rawAgainstCache: "-"
      rawCacheAligned: "-"

  line_color:
    key: '{group_id}_{variant}'
    entries:
      group_1_assign: "#ff0000"
      group_1_iterator: "#ffa500"
      group_1_operatorCallAgainstCache: "#cccc00"
      group_1_operatorCallCacheAligned: "#008000"
      group_1_rawAgainstCache: "#0000ff"
      group_1_rawCacheAligned: "#4b0082"

